/* Generated by AN DISI Unibo */ 
package it.unibo.cargo_service

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargo_service ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				val Timeout = 30000L
				var Io_port_occupied = false
				var System_out_of_service = false
				var Is_engaged = false
				var Is_hold_full = false
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("CARGOSERVICE_HANDLER | Ready")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="start_engage",cond=whenRequest("request_to_load"))
				}	 
				state("start_engage") { //this:State
					action { //it:State
						if(  Io_port_occupied || System_out_of_service  
						 ){answer("request_to_load", "retry_later", "retry_later(0)"   )  
						}
						if(  Is_hold_full  
						 ){answer("request_to_load", "rejected", "rejected(ARG)"   )  
						}
						 Is_engaged = true  
						request("ask_for_slot", "ask_for_slot(ARG)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
