/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice_handler

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice_handler ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				// stato e costanti
				var ServiceWorking = true
				var IOPortOccupied = false
		        var Engaged = false
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("CARGOSERVICE_HANDLER | Ready")
						delay(2000) 
						updateResourceRep(
						            "cargoservice(idle," +
						            "serviceWorking=$ServiceWorking," +
						            "ioportOccupied=$IOPortOccupied)"
										
						)
						forward("show_service_status", "show_service_status(service_working)" ,"display" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("start_engage"))
					transition(edgeName="t01",targetState="resetEngaged",cond=whenDispatch("taskCompleted"))
					transition(edgeName="t02",targetState="system_out_of_service",cond=whenEvent("system_failure"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						CommUtils.outgreen("CARGOSERVICE_HANDLER | Serving")
						if(  !ServiceWorking  
						 ){CommUtils.outgreen("CARGOSERVICE_HANDLER | System set to out of service")
						answer("start_engage", "retrylater", "retrylater(out_of_service)"   )  
						}
						else
						 {if(  IOPortOccupied || Engaged  
						  ){CommUtils.outgreen("CARGOSERVICE_HANDLER | Already Engaged")
						 answer("start_engage", "engage_refused", "engage_refused(ioport_occupied)"   )  
						 }
						 else
						  {CommUtils.outgreen("CARGOSERVICE_HANDLER | System is now engaged")
						   Engaged = true  
						  answer("start_engage", "engage_successful", "engage_successful(ARG)"   )  
						  forward("startWorking", "startWorking(1)" ,"cargoservice_worker" ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("resetEngaged") { //this:State
					action { //it:State
						CommUtils.outgreen("CARGOSERVICE_HANDLER | No more Engaged")
						 Engaged = false  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("system_out_of_service") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("system_failure(ARG)"), Term.createTerm("system_failure(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ServiceWorking = payloadArg(0).toBoolean()  
								CommUtils.outgreen("CARGOSERVICE_HANDLER | System out of service set to $ServiceWorking")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
