/* Generated by AN DISI Unibo */ 
package it.unibo.display

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Display ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var DisplayValue = "none"  
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						updateResourceRep( "display(service_working)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="showHold",cond=whenDispatch("show_hold_state"))
					transition(edgeName="t017",targetState="showService",cond=whenDispatch("show_service_status"))
				}	 
				state("showHold") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("show_hold_state(STATE)"), Term.createTerm("show_hold_state(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                DisplayValue =
								                    "display(hold,${payloadArg(0)})"
						}
						CommUtils.outmagenta("$DisplayValue")
						updateResourceRep( DisplayValue  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("showService") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("show_service_status(STATUS)"), Term.createTerm("show_service_status(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                DisplayValue =
								                    "display(service,${payloadArg(0)})"
						}
						CommUtils.outmagenta("$DisplayValue")
						updateResourceRep( DisplayValue  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
