/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		    	
		    	val slots = mapOf<String, Array<Int>>(
		    		"home" to arrayOf(0, 0),
		    		"io_port" to arrayOf(0, 4),
		    		"slot1" to arrayOf(1, 1),
		    		"slot2" to arrayOf(1, 3),
		    		"slot3" to arrayOf(4, 1),
		    		"slot4" to arrayOf(4, 3),
		    		"marker" to arrayOf(5, 2)
		    	)
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						updateResourceRep( "cargorobot(idle)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="move",cond=whenDispatch("move_container_to_slot"))
					transition(edgeName="t04",targetState="move_robot_done",cond=whenReply("move_robot_done"))
					transition(edgeName="t05",targetState="move_robot_failed",cond=whenReply("move_robot_failed"))
				}	 
				state("move_robot_done") { //this:State
					action { //it:State
						CommUtils.outgreen("Move | OK")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("move_robot_failed") { //this:State
					action { //it:State
						CommUtils.outyellow("Move | BAD")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("move") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("move_container_to_slot(SLOT)"), Term.createTerm("move_container_to_slot(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("CARGOROBOT | Move Requested")
								 
									        	val coord = slots[payloadArg(0)]
								if(  coord != null  
								 ){CommUtils.outgreen("CARGOROBOT | ${coord.get(0)} - ${coord.get(1)}")
								 val (X, Y) = coord  
								request("move_robot", "move_robot($X,$Y,100)" ,"robotsmart" )  
								}
								else
								 {CommUtils.outred("Target not valid")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
