/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				// stato e costanti
				var ServiceWorking = true
				var IOPortOccupied = false
		        var Engaged = false
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | READY")
						updateResourceRep(
						            "cargoservice(idle," +
						            "serviceWorking=$ServiceWorking," +
						            "ioportOccupied=$IOPortOccupied)"
						)
						forward("show_service_status", "show_service_status(service_working)" ,"display" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("load_container"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name SERVING REQUEST")
						if(  !ServiceWorking  
						 ){CommUtils.outred("Out of service")
						answer("load_container", "retrylater", "retrylater(out_of_service)"   )  
						}
						else
						 {if(  IOPortOccupied || Engaged  
						  ){CommUtils.outyellow("Already Engaged")
						 answer("load_container", "retrylater", "retrylater(ioport_occupied)"   )  
						 }
						 else
						  {CommUtils.outyellow("Engaged")
						   Engaged = true  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("acceptRequest") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("refuseRequest") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("moveToSlot5") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("moveToReservedSlot") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("setIOPortOccupied") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("outOfService") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
