/* Generated by AN DISI Unibo */ 
package it.unibo.marker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Marker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "wait"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var CodeNumber = 1  
		return { //this:ActionBasciFsm
				state("wait") { //this:State
					action { //it:State
						updateResourceRep( "marker(idle)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="marking",cond=whenRequest("start_marking"))
				}	 
				state("marking") { //this:State
					action { //it:State
						updateResourceRep( "marker(marking)"  
						)
						CommUtils.outmagenta("MARKER | Marking container...")
						delay(2000) 
						CommUtils.outmagenta("MARKER | Container marked")
						 
									val Code = "code + $CodeNumber" 
									CodeNumber++
						emit("container_marked", "container_marked($Code)" ) 
						updateResourceRep(
						            "marker(completed,code001)"
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
