/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice_worker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice_worker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var Slot = ""
				var Code = ""
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Ready")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="ask_holding",cond=whenDispatch("startWorking"))
				}	 
				state("ask_holding") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Asking for holding...")
						request("ask_for_slot", "ask_for_slot(ARG)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="acceptRequest",cond=whenReply("slot_obtained"))
					transition(edgeName="t15",targetState="refuseRequest",cond=whenReply("slots_unavailable"))
				}	 
				state("refuseRequest") { //this:State
					action { //it:State
						 Slot = ""  
						CommUtils.outyellow("CARGOSERVICE_WORKER | Request refused!")
						forward("taskCompleted", "taskCompleted(ARG)" ,"cargoservice_handler" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("acceptRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slot_obtained(SLOT)"), Term.createTerm("slot_obtained(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Slot = payloadArg(0)  
								CommUtils.outyellow("CARGOSERVICE_WORKER | Request accepted with arg: $Slot")
								CommUtils.outyellow("CARGOSERVICE_WORKER | Moving cargorobot to io port")
								request("moverobot", "moverobot(io_port)" ,"cargorobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t26",targetState="at_io_port",cond=whenReply("moverobotdone"))
					transition(edgeName="t27",targetState="out_of_service",cond=whenReply("moverobotfailed"))
				}	 
				state("at_io_port") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Cargorbot at io port!")
						request("load_container", "load_container(ARG)" ,"io_port" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t48",targetState="move_to_marker",cond=whenReply("load_done"))
				}	 
				state("move_to_marker") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Moving cargorobot to marker")
						request("moverobot", "moverobot(marker)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t39",targetState="at_marker",cond=whenReply("moverobotdone"))
					transition(edgeName="t310",targetState="out_of_service",cond=whenReply("moverobotfailed"))
				}	 
				state("at_marker") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Cargorbot at marker")
						request("start_marking", "start_marking(ARG)" ,"marker" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t511",targetState="move_container_to_slot",cond=whenEvent("container_marked"))
				}	 
				state("move_container_to_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("container_marked(BARCODE)"), Term.createTerm("container_marked(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outyellow("CARGOSERVICE_WORKER | Moving container to its designeted slot")
								request("moverobot", "moverobot($Slot)" ,"cargorobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t612",targetState="move_to_home",cond=whenReply("moverobotdone"))
					transition(edgeName="t613",targetState="out_of_service",cond=whenReply("moverobotfailed"))
				}	 
				state("move_to_home") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Moving cargorobot home")
						forward("container_deployed", "container_deployed(Slot,Code)" ,"hold" ) 
						request("moverobot", "moverobot(home)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t714",targetState="task_finished",cond=whenReply("moverobotdone"))
					transition(edgeName="t715",targetState="out_of_service",cond=whenReply("moverobotfailed"))
				}	 
				state("task_finished") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | Task completed succesfully!")
						 Slot = ""  
						forward("taskCompleted", "taskCompleted(ARG)" ,"cargoservice_handler" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("setIOPortOccupied") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("out_of_service") { //this:State
					action { //it:State
						CommUtils.outyellow("CARGOSERVICE_WORKER | System going out of service!")
						 Slot = ""  
						emit("system_failure", "system_failure(ARG)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
