/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice_worker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice_worker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var Slot = ""	
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | READY")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="acceptRequest",cond=whenDispatch("startWorking"))
				}	 
				state("ask_holding") { //this:State
					action { //it:State
						request("ask_for_slot", "ask_for_slot("")" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="acceptRequest",cond=whenReply("slot_obtained"))
					transition(edgeName="t14",targetState="refuseRequest",cond=whenReply("slots_unavailable"))
				}	 
				state("refuseRequest") { //this:State
					action { //it:State
						 Slot = ""  
						forward("taskCompleted", "taskCompleted("")" ,"cargoservice_handler" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("acceptRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slot_obtained(SLOT)"), Term.createTerm("slot_obtained(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Slot = payloadArg(0)  
								request("moverobot", "moverobot(io_port)" ,"cargorobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t25",targetState="at_io_port",cond=whenReply("moverobotdone"))
					transition(edgeName="t26",targetState="outOfService",cond=whenReply("moverobotfailed"))
				}	 
				state("at_io_port") { //this:State
					action { //it:State
						request("moverobot", "moverobot(marker)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t37",targetState="at_marker",cond=whenReply("moverobotdone"))
					transition(edgeName="t38",targetState="outOfService",cond=whenReply("moverobotfailed"))
				}	 
				state("at_marker") { //this:State
					action { //it:State
						request("moverobot", "moverobot($Slot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t49",targetState="move_to_home",cond=whenReply("moverobotdone"))
					transition(edgeName="t410",targetState="outOfService",cond=whenReply("moverobotfailed"))
				}	 
				state("move_to_home") { //this:State
					action { //it:State
						request("moverobot", "moverobot(home)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t511",targetState="task_finished",cond=whenReply("moverobotdone"))
					transition(edgeName="t512",targetState="outOfService",cond=whenReply("moverobotfailed"))
				}	 
				state("task_finished") { //this:State
					action { //it:State
						 Slot = ""  
						forward("taskCompleted", "taskCompleted("")" ,"cargoservice_handler" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("setIOPortOccupied") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("outOfService") { //this:State
					action { //it:State
						 Slot = ""  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
